---
- name: Configurar y asegurar Active Directory en Windows Server 2022
  hosts: windows
  gather_facts: no

  collections:
    - ansible.windows
    - community.windows
    - microsoft.ad

  vars:
    domain_name: "chrisyjaime.com.mx"
    password_policy_min_length: 8
    password_policy_history: 5
    password_policy_complexity: true

  tasks:
    - name: Crear Organizational Unit (OU) para Empleados
      microsoft.ad.ou:
        name: "Empleados"
        path: "DC=chrisyjaime,DC=com,DC=mx"
        state: present

    - name: Crear Organizational Unit (OU) para Soporte Tecnico
      microsoft.ad.ou:
        name: "Soporte Tecnico"
        path: "DC=chrisyjaime,DC=com,DC=mx"
        state: present

    - name: Crear Organizational Unit (OU) para Manager
      microsoft.ad.ou:
        name: "Manager"
        path: "DC=chrisyjaime,DC=com,DC=mx"
        state: present

    - name: Crear Organizational Unit (OU) para IT
      microsoft.ad.ou:
        name: "IT"
        path: "DC=chrisyjaime,DC=com,DC=mx"
        state: present

    - name: Crear grupo global "Empleados"
      microsoft.ad.group:
        name: "Empleados"
        scope: "global"
        state: present

    - name: Crear grupo global "ITAdmins"
      microsoft.ad.group:
        name: "ITAdmins"
        scope: "global"
        state: present
        members:
          add:
            - "administrator"

    - name: Crear grupo universal "Administrators"
      microsoft.ad.group:
        name: "Administrators"
        scope: "universal"
        state: present
        members:
          add:
            - "administrator"

    - name: Crear grupo "DomainLocal" y asignar permisos a los grupos globales
      microsoft.ad.group:
        name: "LocalUsers"
        scope: "domainlocal"
        state: present
        members:
          add:
            - "Empleados"
            - "ITAdmins"  # Se agregan los grupos globales al grupo DomainLocal

    - name: Crear usuario "user1" en AD
      microsoft.ad.user:
        name: "user1"
        given_name: "User"
        surname: "One"
        full_name: "User One"
        password: "P@ssw0rd123"
        state: present
        user_cannot_change_password: no
        password_never_expires: no
        groups:
          add:
            - "Empleados"

    - name: Crear usuario "user2" en AD
      microsoft.ad.user:
        name: "user2"
        given_name: "User"
        surname: "Two"
        full_name: "User Two"
        password: "SecurePassword456"
        state: present
        user_cannot_change_password: no
        password_never_expires: no
        groups:
          add:
            - "ITAdmins"

    - name: Configurar política de longitud mínima de contraseña
      win_shell: net accounts /minpwlen:{{ password_policy_min_length }}

    - name: Configurar historial de contraseñas
      win_shell: net accounts /uniquepw:{{ password_policy_history }}

    - name: Habilitar complejidad de contraseñas
      win_regedit:
        path: HKLM\SYSTEM\CurrentControlSet\Control\Lsa
        name: PasswordComplexity
        data: "{{ 1 if password_policy_complexity else 0 }}"
        type: dword
        state: present

    - name: Configurar política de bloqueo de cuenta - intentos fallidos
      win_shell: net accounts /lockoutthreshold:5

    - name: Configurar política de bloqueo de cuenta - duración
      win_shell: net accounts /lockoutduration:15

    - name: Configurar política de bloqueo de cuenta - restablecer contador
      win_shell: net accounts /lockoutwindow:15

    - name: Configurar Auditoría de inicio/cierre de sesión
      win_audit_policy_system:
        category: Logon/Logoff
        subcategory: Logon
        audit_type: Success,Failure

    - name: Configurar Auditoría de acceso a objetos (Archivos)
      win_audit_policy_system:
        category: Object Access
        subcategory: File System
        audit_type: Success,Failure

    - name: Establecer usuarios con denegación de inicio de sesión interactivo
      ansible.windows.win_user_right:
        name: SeDenyInteractiveLogonRight
        users:
          - "User1"
        state: present

    - name: Configurar auditoría de acceso a cuentas de usuario
      win_audit_policy_system:
        category: Account Logon
        subcategory: Special Logon
        audit_type: Success,Failure

    - name: Configurar máxima expiración de contraseña
      win_shell: net accounts /maxpwage:60

    - name: Configurar usuario para que su contraseña nunca expire
      win_shell: net user user1 /passwordchg:yes /passwordreq:yes /expires:never