---
- name: Configurar y asegurar Active Directory en Windows Server 2022
  hosts: windows
  gather_facts: no

  collections:
    - ansible.windows
    - community.windows
    - microsoft.ad

  vars:
    domain_name: chrisyjaime.local
    netbios_name: CJ_DC
    safe_mode_password: 'ChrisAdmin1853'
    admin_group: "Domain Admins"
    ou_users: "OU=Users,DC=chrisyjaime,DC=local"
    ou_groups: "OU=Groups,DC=chrisyjaime,DC=local"
    ou_computers: "OU=Computers,DC=chrisyjaime,DC=local"
    ou_it: "OU=IT,DC=chrisyjaime,DC=local"
    password_policy_min_length: 12
    password_policy_complexity: yes
    password_policy_history: 24

  tasks:
    - name: Instalar el rol de Active Directory Domain Services (AD DS)
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: Promocionar el servidor a controlador de dominio (si no lo es ya)
      microsoft.ad.domain:
        dns_domain_name: "{{ domain_name }}"
        domain_netbios_name: "{{ netbios_name }}"
        safe_mode_password: "{{ safe_mode_password }}"
        create_dns_delegation: no
        install_dns: yes
        reboot: yes
        sysvol_path: "C:\\Windows\\SYSVOL"
        database_path: "C:\\Windows\\NTDS"
        log_path: "C:\\Windows\\NTDS"
        domain_mode: "Default"
        forest_mode: "Default"

    - name: Crear Organizational Unit (OU) para Usuarios
      microsoft.ad.ou:
        name: "Empleados"
        path: "DC=chrisyjaime,DC=local"
        state: present

    - name: Crear Organizational Unit (OU) para Grupos
      microsoft.ad.ou:
        name: ""
        path: "DC=chrisyjaime,DC=local"
        state: present

    - name: Crear Organizational Unit (OU) para Computadoras
      microsoft.ad.ou:
        name: "Computers"
        path: "DC=chrisyjaime,DC=local"
        state: present

    - name: Crear Organizational Unit (OU) para IT
      microsoft.ad.ou:
        name: "IT"
        path: "DC=chrisyjaime,DC=local"
        state: present

    - name: Crear grupo de seguridad local "Administradores"
      microsoft.ad.group:
        name: "Administrators"
        state: present
        members:
          - "Administrator"

    - name: Crear grupo global "Usuarios"
      microsoft.ad.group:
        name: "Users"
        domain: "{{ domain_name }}"
        group_scope: "Global"
        state: present

    - name: Crear grupo universal "ITAdmins"
      microsoft.ad.group:
        name: "ITAdmins"
        domain: "{{ domain_name }}"
        group_scope: "Universal"
        state: present
        members:
          - "Administrator"
          - "User1" # Ejemplo de miembro

    - name: Crear grupo "Domain Admins"
      microsoft.ad.group:
        name: "{{ admin_group }}"
        domain: "{{ domain_name }}"
        group_scope: "Global"
        state: present
        members:
          - "Administrator"

    - name: Crear usuario "user1" en AD
      microsoft.ad.user:
        name: "user1"
        given_name: "User"
        surname: "One"
        full_name: "User One"
        password: "P@ssw0rd123"
        state: present
        user_cannot_change_password: no
        password_never_expires: no
        groups:
          - "Users"
          - "{{ admin_group }}" # Ejemplo de asignación de grupo

    - name: Crear usuario "user2" en AD
      microsoft.ad.user:
        name: "user2"
        given_name: "User"
        surname: "Two"
        full_name: "User Two"
        password: "SecurePassword456"
        state: present
        user_cannot_change_password: no
        password_never_expires: no
        groups:
          - "Users"

    - name: Configurar política de longitud mínima de contraseña
      win_shell: net accounts /minpwlen:{{ password_policy_min_length }}

    - name: Configurar historial de contraseñas
      win_shell: net accounts /uniquepw:{{ password_policy_history }}

    - name: Habilitar complejidad de contraseñas
      win_regedit:
        path: HKLM\SYSTEM\CurrentControlSet\Control\Lsa
        name: PasswordComplexity
        data: "{{ 1 if password_policy_complexity else 0 }}"
        type: dword
        state: present

    - name: Configurar política de bloqueo de cuenta - intentos fallidos
      win_shell: net accounts /lockoutthreshold:5

    - name: Configurar política de bloqueo de cuenta - duración
      win_shell: net accounts /lockoutduration:15

    - name: Configurar política de bloqueo de cuenta - restablecer contador
      win_shell: net accounts /lockoutwindow:15

    - name: Configurar Auditoría de inicio/cierre de sesión
      win_audit_policy_system:
        category: Logon/Logoff
        subcategory: Logon
        audit_type: Success,Failure

    - name: Configurar Auditoría de acceso a objetos (Archivos)
      win_audit_policy_system:
        category: Object Access
        subcategory: File System
        audit_type: Success,Failure

    - name: Establecer usuarios con denegación de inicio de sesión interactivo
      ansible.windows.win_user_right:
        name: SeDenyInteractiveLogonRight
        users:
          - "User1"
        state: present

    - name: Configurar auditoría de acceso a cuentas de usuario
      win_audit_policy_system:
        category: Account Logon
        subcategory: Special Logon
        audit_type: Success,Failure

    - name: Configurar máxima expiración de contraseña
      win_shell: net accounts /maxpwage:60

    - name: Configurar usuario para que su contraseña nunca expire
      win_shell: net user user1 /passwordchg:yes /passwordreq:yes /expires:never