- name: DNS avanzado en Windows Server 2022
  hosts: windows
  gather_facts: no

  collections:
    - ansible.windows
    - community.windows

  vars:
    dns_zone_name: "chrisyjaime.local"
    reverse_zone_name: "16.0.10.in-addr.arpa"
    dns_forwarders:
      - "8.8.8.8"
      - "1.1.1.1"
    dns_records:
      - name: "web"
        ip: "10.0.16.10"
      - name: "db"
        ip: "10.0.16.11"
      - name: "fileshare"
        ip: "10.0.16.12"

  tasks:

    - name: Instalar rol de DNS Server
      win_feature:
        name: DNS
        state: present
        include_management_tools: yes

    - name: Crear zona directa primaria
      win_dns_zone:
        name: "{{ dns_zone_name }}"
        type: Primary
        state: present

    - name: Crear zona inversa primaria
      win_dns_zone:
        name: "{{ reverse_zone_name }}"
        type: Primary
        state: present

    - name: Agregar registros A en la zona directa
      win_dns_record:
        zone: "{{ dns_zone_name }}"
        name: "{{ item.name }}"
        type: A
        value: "{{ item.ip }}"
        state: present
      loop: "{{ dns_records }}"

    - name: Agregar registros PTR en la zona inversa
      win_dns_record:
        zone: "{{ reverse_zone_name }}"
        name: "{{ item.ip.split('.')[3] }}"
        type: PTR
        value: "{{ item.name }}.{{ dns_zone_name }}"
        state: present
      loop: "{{ dns_records }}"

    - name: Configurar reenviadores DNS
      win_dns_client:
        interface_alias: "Ethernet"
        dns_servers: "{{ dns_forwarders }}"

    - name: Permitir tráfico DNS TCP por firewall
      win_firewall_rule:
        name: "Allow DNS TCP"
        localport: 53
        action: allow
        direction: in
        protocol: TCP
        state: present

    - name: Permitir tráfico DNS UDP por firewall
      win_firewall_rule:
        name: "Allow DNS UDP"
        localport: 53
        action: allow
        direction: in
        protocol: UDP
        state: present