---
- name: Setup MySQL Server with Advanced Configuration and Security
  hosts: all
  become: yes

  tasks:
    - name: Instalar PyMySQL para que Ansible pueda usar los módulos MySQL
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Instalar MySQL Server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Habilitar y arrancar MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Configurar contraseña compleja y plugin para root (login con contraseña)
      mysql_user:
        name: root
        host: localhost
        password: "ElAdmin1853"
        plugin: mysql_native_password
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present

    - name: Crear base de datos "testdb"
      mysql_db:
        name: testdb
        state: present
        login_user: root
        login_password: "ElAdmin1853"

    - name: Crear tabla de prueba "users" en "testdb"
      mysql_query:
        query: |
          CREATE TABLE IF NOT EXISTS testdb.users (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            email VARCHAR(100) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );
        login_user: root
        login_password: "ElAdmin1853"

    - name: Insertar datos de prueba en la tabla "users"
      mysql_query:
        query: |
          INSERT INTO testdb.users (name, email)
          VALUES ('John Doe', 'john.doe@example.com'),
                  ('Jane Smith', 'jane.smith@example.com'),
                  ('Emily Johnson', 'emily.johnson@example.com');
        login_user: root
        login_password: "ElAdmin1853"

    - name: Crear base de datos "mydb"
      mysql_db:
        name: mydb
        state: present
        login_user: root
        login_password: "ElAdmin1853"

    - name: Crear usuario con todos los privilegios en testdb
      mysql_user:
        name: myuser
        password: securepassword
        host: "%"
        priv: "testdb.*:ALL"
        state: present
        login_user: root
        login_password: "ElAdmin1853"

    - name: Crear usuario solo lectura en testdb
      mysql_user:
        name: mysql_user2
        password: readpassword
        host: "%"
        priv: "testdb.*:SELECT"
        state: present
        login_user: root
        login_password: "ElAdmin1853"

    - name: Crear usuario solo escritura en testdb
      mysql_user:
        name: mysql_user3
        password: writepassword
        host: "%"
        priv: "testdb.*:INSERT,UPDATE"
        state: present
        login_user: root
        login_password: "ElAdmin1853"

    - name: Instalar fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Crear grupo de administración ACL para usuarios de MySQL
      group:
        name: mysqladmins
        state: present

    - name: Establecer secure_file_priv para exportaciones
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^secure_file_priv'
        line: 'secure_file_priv = /var/lib/mysql-files'
      notify: Restart MySQL

    - name: Configurar UFW - permitir SSH
      ufw:
        rule: allow
        port: 22

    - name: Habilitar y permitir acceso al puerto 3306 (MySQL)
      ufw:
        state: enabled
        rule: allow
        port: 3306
        proto: tcp

    - name: Habilitar plugin de auditoría nativa de MySQL
      mysql_query:
        query: "INSTALL PLUGIN audit_log SONAME 'audit_log.so';"
        login_user: root
        login_password: "ElAdmin1853"
      ignore_errors: yes  # Evita fallos si ya está instalado

    - name: Crear archivo de log de auditoría si no existe
      file:
        path: /var/log/mysql/audit.log
        state: touch
        owner: mysql
        group: adm
        mode: '0640'

    - name: Configurar auditoría básica en mysqld.cnf (MySQL nativo)
      blockinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        block: |
          audit_log_file = /var/log/mysql/audit.log
          audit_log_format = JSON
          audit_log_policy = ALL
      notify:
        - Restart MySQL