---
- name: Configurar Active Directory en Windows Server 2022
  hosts: windows
  gather_facts: no

  vars:
    domain_name: corp.local
    netbios_name: CORP
    safe_mode_password: 'Chris1853'

  tasks:
    - name: Instalar el rol de AD DS
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: Promocionar a controlador de dominio (solo si no lo es ya)
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_netbios_name: "{{ netbios_name }}"
        safe_mode_password: "{{ safe_mode_password }}"
        state: domain_controller
        reboot: yes